# Generated by `cargo run -p intensify-pyo3 --bin stub-gen`.
# ruff: noqa: E704
from __future__ import annotations

from types import ModuleType
from typing import Any

ArrayLike = Any
NDArray = Any

class _ExponentialKernel:
    alpha: float
    beta: float
    allow_signed: bool
    def __init__(
        self, alpha: float, beta: float, *, allow_signed: bool = False
    ) -> None: ...
    def evaluate(self, t: ArrayLike) -> NDArray: ...
    def integrate(self, t: float) -> float: ...
    def integrate_vec(self, t: ArrayLike) -> NDArray: ...
    def l1_norm(self) -> float: ...
    def scale(self, factor: float) -> None: ...
    def has_recursive_form(self) -> bool: ...
    def recursive_state_update(self, state: float, dt: float) -> float: ...
    def recursive_decay(self, state: float, dt: float) -> float: ...
    def recursive_absorb(self, state: float) -> float: ...
    def recursive_intensity_excitation(self, state: float) -> float: ...

class _PowerLawKernel:
    alpha: float
    beta: float
    c: float
    def __init__(self, alpha: float, beta: float, c: float = 1.0) -> None: ...
    def evaluate(self, t: ArrayLike) -> NDArray: ...
    def integrate(self, t: float) -> float: ...
    def integrate_vec(self, t: ArrayLike) -> NDArray: ...
    def l1_norm(self) -> float: ...
    def scale(self, factor: float) -> None: ...
    def has_recursive_form(self) -> bool: ...

class _NonparametricKernel:
    edges: NDArray
    values: NDArray
    n_bins: int
    def __init__(self, edges: ArrayLike, values: ArrayLike) -> None: ...
    def evaluate(self, t: ArrayLike) -> NDArray: ...
    def integrate(self, t: float) -> float: ...
    def integrate_vec(self, t: ArrayLike) -> NDArray: ...
    def l1_norm(self) -> float: ...
    def scale(self, factor: float) -> None: ...
    def has_recursive_form(self) -> bool: ...

class _MvExpRecursiveLogLik:
    n_dims: int
    end_time: float
    decay: float
    n_total_jumps: int
    n_coeffs: int
    def __init__(
        self, timestamps: list[ArrayLike], end_time: float, decay: float
    ) -> None: ...
    def loss_and_grad(self, coeffs: ArrayLike, out: NDArray) -> float: ...
    def loss(self, coeffs: ArrayLike) -> float: ...

class _Kernels(ModuleType):
    ExponentialKernel: type[_ExponentialKernel]
    PowerLawKernel: type[_PowerLawKernel]
    NonparametricKernel: type[_NonparametricKernel]

class _Likelihood(ModuleType):
    MvExpRecursiveLogLik: type[_MvExpRecursiveLogLik]
    def uni_exp_neg_ll_with_grad(
        self, times: ArrayLike, t_horizon: float, mu: float, alpha: float, beta: float
    ) -> tuple[float, NDArray]: ...
    def uni_exp_neg_ll(
        self, times: ArrayLike, t_horizon: float, mu: float, alpha: float, beta: float
    ) -> float: ...
    def mv_exp_dense_neg_ll_with_grad(
        self,
        times: ArrayLike,
        sources: ArrayLike,
        end_time: float,
        n_dims: int,
        mu: ArrayLike,
        alpha: ArrayLike,
        beta: ArrayLike,
    ) -> tuple[float, NDArray, NDArray, NDArray]: ...
    def mv_exp_dense_neg_ll(
        self,
        times: ArrayLike,
        sources: ArrayLike,
        end_time: float,
        n_dims: int,
        mu: ArrayLike,
        alpha: ArrayLike,
        beta: ArrayLike,
    ) -> float: ...
    def uni_powerlaw_neg_ll_with_grad(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
        c: float,
    ) -> tuple[float, NDArray]: ...
    def uni_powerlaw_neg_ll(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
        c: float,
    ) -> float: ...
    def uni_nonparametric_neg_ll_with_grad(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        edges: ArrayLike,
        values: ArrayLike,
    ) -> tuple[float, NDArray]: ...
    def uni_nonparametric_neg_ll(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        edges: ArrayLike,
        values: ArrayLike,
    ) -> float: ...
    def uni_sumexp_neg_ll_with_grad(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alphas: ArrayLike,
        betas: ArrayLike,
    ) -> tuple[float, NDArray]: ...
    def uni_sumexp_neg_ll(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alphas: ArrayLike,
        betas: ArrayLike,
    ) -> float: ...
    def marked_uni_exp_neg_ll_with_grad(
        self,
        times: ArrayLike,
        marks: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
    ) -> tuple[float, NDArray]: ...
    def marked_uni_exp_neg_ll(
        self,
        times: ArrayLike,
        marks: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
    ) -> float: ...
    def uni_approx_powerlaw_neg_ll_with_grad(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta_pow: float,
        beta_min: float,
        r: float,
        n_components: int,
    ) -> tuple[float, NDArray]: ...
    def uni_approx_powerlaw_neg_ll(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta_pow: float,
        beta_min: float,
        r: float,
        n_components: int,
    ) -> float: ...
    def nonlinear_uni_exp_neg_ll_with_grad(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
        link_kind: str,
        sigmoid_scale: float,
        n_quad: int,
    ) -> tuple[float, NDArray]: ...
    def nonlinear_uni_exp_neg_ll(
        self,
        times: ArrayLike,
        t_horizon: float,
        mu: float,
        alpha: float,
        beta: float,
        link_kind: str,
        sigmoid_scale: float,
        n_quad: int,
    ) -> float: ...

class _Simulation(ModuleType):
    def simulate_uni_exp_hawkes(
        self, t_horizon: float, mu: float, alpha: float, beta: float, seed: int
    ) -> NDArray: ...
    def simulate_mv_exp_hawkes(
        self, t_horizon: float, mu: ArrayLike, alpha: ArrayLike, beta: float, seed: int
    ) -> list[NDArray]: ...
    def simulate_uni_exp_branching(
        self, t_horizon: float, mu: float, alpha: float, beta: float, seed: int
    ) -> NDArray: ...
    def simulate_mv_exp_branching(
        self, t_horizon: float, mu: ArrayLike, alpha: ArrayLike, beta: float, seed: int
    ) -> list[NDArray]: ...

kernels: _Kernels
likelihood: _Likelihood
simulation: _Simulation
diagnostics: ModuleType
